Fix innodb-buffer-size error
canonical/ua-reviewkit pull request #20
Opened 2022-03-23 18:01 UTC by sombrafam

Especially with Kubernetes, we are using mysql-innodb-cluster
only for Vault storage backend. The default value is actually
sufficient. So, changing it from FAIL -> WARN.

Closes #8

2022-03-31 10:51 UTC, dosaboy requested changes

2022-08-05 08:27 UTC, dosaboy commented
@sombrafam any update on this?

2022-08-09 19:00 UTC, sombrafam commented on juju/checks/openstack.yaml
> +          warn-on-fail: true
Yes, I got confused from the bug description. Also, the FE that was running was running without --type kubernetes, so was running the openstack checks instead of kubernetes. I'm submitting another patch.

2022-08-09 19:04 UTC, sombrafam commented on juju/checks/openstack.yaml
> +          warn-on-fail: true
Ill abandon this PR since was pushed in a wrong branch.

2022-08-09 19:04 UTC, closed without merging

2022-08-09 19:05 UTC, sombrafam commented on juju/checks/openstack.yaml
> +          warn-on-fail: true
Replacement: https://github.com/canonical/ua-reviewkit/pull/23